### ISSUE TITLE
Wallet Bip32 generation

### ISSUE THREAD

**Issue by ghost** [bitcoinfs/bitcoinfs#3]
I'm looking at F# for the first time because I find such a short implementation very interesting, but the syntax is a little foreign to me.

How would I, given an electrum 12-key seed, generate a list of private/public keys and addresses?

**Comment by hhanh00** [comment]
Bip32 doesn't use a 12-word seed but a seed value. Bip 39 specifies a transformation from a 12 word seed to a 128-bit seed but it's not used by Electrum.
However, Electrum can show you the master public key. It should be a 512 bit hex string of the form `xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy`

```
let mpkBip32 = Hex.Decode("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx")
let mpkBip32Chain = Hex.Decode("yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy")

let myHashes = bip32Hashes mpkBip32 mpkBip32Chain true 100
```

**Comment by ghost** [comment]
Okay, and you would then push the hashes through toAddress, right?

How about for deriving a list of private keys?

**Comment by hhanh00** [comment]
You can use the `BIP32PrivKeyExt` type.

```
let privKeySeq (secret: byte[]) (chain: byte[]) (c: int) =
    let privKeyExt = (new BIP32PrivKeyExt(new Org.BouncyCastle.Math.BigInteger(1, secret), chain))
    seq { 
        for i in 0..c-1 do
            yield privKeyExt.ToPrivChild(i)
        }
```
