### ISSUE TITLE
Missing json files for tests

### ISSUE THREAD

**Issue by raymens** [bitcoinfs/bitcoinfs#6]
To run the tests the following files seem to be required but are missing from the repo:
- /data/script_valid.json
- /data/script_invalid.json
- /data/sighash.json
- /data/tx_valid.json
- /data/tx_invalid.json
- /data/sig_canonical.json

Could you supply these or tell what's supposed to be in it?

**Comment by hhanh00** [comment]
These guys come from the official bitcoin release. They are part of their unit tests.

**Comment by raymens** [comment]
Thanks, found them except the sig_canonical.json one.
Doesn't seem to be located at https://github.com/bitcoin/bitcoin/tree/master/src/test/data

**Comment by bitcoinfs** [comment]
Strange... Nbitcoin still has it though
https://github.com/NicolasDorier/NBitcoin/tree/master/NBitcoin.Tests/data

**Comment by raymens** [comment]
Deleted at https://github.com/bitcoin/bitcoin/commit/d6bed1514c2e72ea2006942c23c31e3f518d4a77
Doesn't seem to state why though...

Anyway, thanks :+1:
