### ISSUE TITLE
Loads of Script Failures

### ISSUE THREAD

**Issue by raymens** [bitcoinfs/bitcoinfs#7]
Hello again ;)

So I'm trying to get this all to work as I think it's a great project but I just need to figure some stuff out.
Currently I'm getting a bunch of script failures, I've added some logging to know what transactions are failing. The transactions that are failing (seems like all of them) are created just now. So for me it seems they are transactions that have just been propagated by the peers. I'm starting the node with an empty blockchain (no bootstrapping etc.). So my thought would be that maybe it's trying to validate the transactions but is missing the proper inputs because it hasn't catched up yet?

Some output:
https://gist.github.com/raymens/e84106694e01ec61c7c6

**Comment by hhanh00** [comment]
Yes, if the block validation pass then they must be coming from the mempool. These transactions will be rejected. Personally, I comment out the mempool when I do a long sync.

**Comment by raymens** [comment]
Thanks for the clarification!
